name: hearts # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.5.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: The classic hearts card game.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots   
apps:
    hearts:
     common-id: org.kde.hearts.desktop
     command: ./Hearts
     extensions:
      - kde-neon
     plugs:
      - x11
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - opengl
      - audio-playback
      - home
parts:
     # See 'snapcraft plugins'
    heartsicon:
     plugin: nil
     override-prime: | 
      cp /root/parts/hearts/build/SVG-cards/Default/back.png /root/prime/back.png
      sudo xdg-icon-resource install --novendor --size 64 /root/prime/back.png hearts
      cp /usr/share/icons/hicolor/64x64/apps/hearts.png /root/prime/hearts.png
     build-packages:
      - xdg-utils
    hearts:
     source: https://github.com/Rescator7/Hearts.git
     source-type: git
     plugin: qmake
     override-build: |
      snapcraftctl build
      mv Hearts *.o /root/prime/    
     build-packages:
      [ liballegro5-dev, g++, liballegro-audio5-dev, liballegro-acodec5-dev]
     stage-packages:
      [ liballegro-audio5.2, liballegro-acodec5.2, libqt5widgets5]
     build-snaps:
      - kde-frameworks-5-core18-sdk
      - kde-frameworks-5-core18
