name: hearts # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.9.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: The classic hearts card game.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
apps:
    hearts:
     common-id: org.kde.hearts.desktop
     command: ./Hearts
     extensions:
      - kde-neon
     plugs:
      - x11
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - opengl
      - audio-playback
      - home
      - network
      - network-bind
parts:
     # See 'snapcraft plugins'
    heartsicon:
     plugin: nil

     build-packages:
      - xdg-utils
    hearts:
     source: https://github.com/Rescator7/Hearts.git
     source-type: git
     plugin: qmake
     override-build: |
      snapcraftctl build
      mv Hearts *.o $SNAPCRAFT_PRIME/
      cp $SNAPCRAFT_PART_SRC/SVG-cards/Default/back.png $SNAPCRAFT_PRIME/back.png
      sudo mkdir -p /usr/share/icons/hicolor
      sudo xdg-icon-resource install --novendor --size 64 $SNAPCRAFT_PRIME/back.png hearts
      cp /usr/share/icons/hicolor/64x64/apps/hearts.png $SNAPCRAFT_PRIME/hearts.png
     build-packages:
      [ liballegro5-dev, g++, liballegro-audio5-dev, liballegro-acodec5-dev, libqt5svg5-dev,qtbase5-dev,qttools5-dev-tools]
     stage-packages:
      [ liballegro-audio5.2, liballegro-acodec5.2, libqt5svg5]
     build-snaps:
      - kde-frameworks-5-core18-sdk
      - kde-frameworks-5-core18
